### ISSUE TITLE
Support for Typescript typings

### ISSUE THREAD

**Issue by stevenzeck** [nanovazquez/yargs-interactive#12]
@nanovazquez I don't know how familiar you are with Typescript, but I opened a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27155) at DefinitelyTyped to have typings for yargs-interactive.  I need to update it now that `options` is `choices`.  But I'm thinking the interfaces should probably extend from inquirer at some point.  I'm just not sure what all is passed from yargs-interactive to inquirer here.  Any input on that PR would be helpful.

**Comment by szeck87** [comment]
It's basically a giant repository of typings for projects that aren't written in Typescript or don't provide their own typings.  I had to create my own for https://github.com/Unibeautify/create-unibeautify-beautifier/blob/master/src/create-unibeautify-beautifier.ts so I had typings and didn't have to use `require()`.

Since `choices` is in inquirer, the `OptionData` interface I have should probably extend inquirer's [Question](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3177220fa4272a8c35ca658c8a250d44eb4ea01d/types/inquirer/index.d.ts#L77) interface.  I'm not an expert on `.d.ts` files, but that's a the gist of it.

**Comment by nanovazquez** [comment]
Closing this issues as the typings [are already present in DefintelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8ba2ecb239ed9fd3c204ed57b8f09d1590e841e8/types/yargs-interactive/index.d.ts). Thanks @stevenzeck!
