### ISSUE TITLE
Following your example adding --interactive doesn't allow interactive mode

### ISSUE THREAD

**Issue by allenchuang** [nanovazquez/yargs-interactive#41]
^ like what title says.

I'm trying to enter interactive mode, but whatever I do, i can't. Am I missing something here?

i saved the file like so in `test.js`
```#!/usr/bin/env node

const yargsInteractive = require("yargs-interactive");
const options = {
  interactive: { default: true },
  name: { type: "input", default: "A robot", describe: "Enter your name" },
  likesPizza: {
    type: "confirm",
    default: false,
    describe: "Do you like pizza?",
  },
};

yargsInteractive()
  .usage("$0 <command> [args]")
  .interactive(options)
  .then((result) => {
    // Your business logic goes here.
    // Get the arguments from the result
    // e.g. myCli(result.name);
    console.log(
      `\nResult is:\n` +
        `- Name: ${result.name}\n` +
        `- Likes pizza: ${result.likesPizza}\n`
    );
  });
```

then i run 

`node test.js --interactive`

outputs immediately without prompts:

```

Result is:
- Name: A robot
- Likes pizza: false

```

**Comment by nanovazquez** [comment]
Thanks for reporting! There is something weird indeed, I'm not sure if the bug was always there or something changed in the yargs API. Just in case, I've added a patch in the code to make sure Interactive mode is triggered if you explicitly asked for it via arguments.

BTW, we are working on a complete refactor and cleanup, using TypeScript, and a better testing strategy, this is why you don't see any test in the commit that fixes the issue (will be included in the next major). Stay tuned!

**Comment by sinkcup** [comment]
me too, it seems there is no new tag for this version. @nanovazquez 

<img width="230" alt="image" src="https://user-images.githubusercontent.com/4971414/158105065-34a1bbad-2f61-4ea5-9cfd-f4cd5d8f45b7.png">
